server:
  port: 8091
spring:
  application:
    name: kafka-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
      bindings:
        producerOutput:
          destination: test
